/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        tertiary: '#006229',
        'inverse-surface': '#213145',
        outline: '#737686',
        'on-secondary': '#ffffff',
        'on-surface': '#0b1c30',
        'tertiary-fixed': '#6bff8f',
        'on-surface-variant': '#434655',
        secondary: '#565e74',
        'surface-bright': '#f8f9ff',
        'tertiary-container': '#007e37',
        'secondary-fixed-dim': '#bec6e0',
        'on-error': '#ffffff',
        'on-background': '#0b1c30',
        'on-tertiary': '#ffffff',
        'surface-tint': '#0053db',
        primary: '#004ac6',
        'on-tertiary-fixed-variant': '#005321',
        'secondary-fixed': '#dae2fd',
        'surface-container-high': '#dce9ff',
        'on-tertiary-container': '#c1ffc5',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed-variant': '#003ea8',
        'surface-container-highest': '#d3e4fe',
        'on-secondary-container': '#5c647a',
        'on-error-container': '#93000a',
        'surface-dim': '#cbdbf5',
        'on-secondary-fixed': '#131b2e',
        'secondary-container': '#dae2fd',
        'inverse-primary': '#b4c5ff',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#00174b',
        surface: '#f8f9ff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-primary-container': '#eeefff',
        'tertiary-fixed-dim': '#4ae176',
        background: '#f8f9ff',
        'surface-variant': '#d3e4fe',
        'outline-variant': '#c3c6d7',
        'primary-container': '#2563eb',
        'surface-container-low': '#eff4ff',
        'primary-fixed': '#dbe1ff',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#002109',
        'inverse-on-surface': '#eaf1ff',
        'on-secondary-fixed-variant': '#3f465c',
        'surface-container': '#e5eeff',
      },
      spacing: {
        xl: '32px',
        lg: '24px',
        'player-padding': '20px',
        base: '4px',
        xs: '4px',
        md: '16px',
        'grid-margin': '24px',
        sm: '8px',
        'grid-gutter': '16px',
      },
      fontFamily: {
        'label-md': ['Inter', 'system-ui', 'sans-serif'],
        'title-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-sm': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'display-lg': ['Inter', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', 'sans-serif'],
        'title-lg': ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}

